### ISSUE TITLE
Information on programmers/programming

### ISSUE THREAD

**Issue by HVR88** [Kalidomra/SuperClone-5.0#1]
Please add some information on sourcing programmer hardware for use with the chips in the BOM that will work on modern hardware. Likely needs to be USB.

I'd love to build one of these as the parts sourcing and soldering look fairly basic, but programming the PROMs is likely to be a challenge for anyone not already set up with dedicated hardware/software to do so.

**Comment by Kalidomra** [comment]
I use a TOP3000 USB programmer to program both the .JED file to the ATF16V8B-15PU and the Super Snapshot .BIN file to the W27C512-45Z. These are available on Ebay or AliExpress. A TL866 programmer is also showing that it supports both of theses devices. The TL866 seems to be cheaper, but I have not tested it.

**Comment by HVR88** [comment]
Have you by any chance tried PCBWay for the PCB build?

**Comment by Kalidomra** [comment]
No. I have used jlcpcb.com
