### ISSUE TITLE
8K / 32K RAM, Jumper configuration 

### ISSUE THREAD

**Issue by MarkusPlehn** [Kalidomra/SuperClone-5.0#3]
I am not sure about the correct Jumper config for 8 or 32 K RAM.
Could you specify this please?

Thanks for this nice Replica 🙂

**Comment by Kalidomra** [comment]
J1 Config:

8K RAM:    1-2
32K RAM:  2-3

Pin 1 of the Jumper is close to the "J1" text and Pin 3 is closest to the cartridge port.

![Jumper](https://user-images.githubusercontent.com/40541205/175385929-97592515-65b1-4dc4-bd8c-17b31f2037c3.jpg)
