### ISSUE TITLE
EPROM compatibility 

### ISSUE THREAD

**Issue by Scyllinice** [Kalidomra/SuperClone-5.0#5]
I've got some spare 27C020s. Would one work in place of the 27C512?

**Comment by Kalidomra** [comment]
They may work, the board is set up for them. That being said, I have not tried that configuration. At a minimum you should program 4 copies of the regular ROM to the 27C020 to fill the whole EPROM.

**Comment by Scyllinice** [comment]
Thanks. I'll report back as soon as the board arrives and I build it.

**Comment by Scyllinice** [comment]
@Kalidomra I can confirm that the 27C020 worked fine.

I ended up having to get a new programmer (A XGecu T48) to program the ATF16V8B-15PU, but everything works great.

Thanks for your work on this project!

**Comment by Kalidomra** [comment]
Do you know the speed of the 27C020 you used? Maybe the complete part number so I can update the readme.

**Comment by Scyllinice** [comment]
I used a `W27C020-70Z`
