### ISSUE TITLE
Snappy V531 NTSC ROM not working on SuperClone board.

### ISSUE THREAD

**Issue by Robert-Di-Benedetto** [Kalidomra/SuperClone-5.0#6]
Flashed an AT29C010A-12PC 128KB ROM with Snappy V531 NTSC binary.  Flash was verified to correctly match the binary.  Also examined a dump to manually verify.

Installed in a known good working SuperClone board that has SS V5.22 ROM.  Boots to a black screen.  Tried with both 8K and 32K RAM configurations.  Reinstalled original V5.22 ROM and all is working fine.

Also submitting this issue on the Snappy (Adrian Gonzalez) GIT area.

**Comment by Kalidomra** [comment]
I have not tested either the new binary or a AT29C010A-12PC. However, looking at the datasheet it is a 120ns part. It may be too slow for the SuperClone. The W27C512-45Z that I have used is 45ns. That also may explain why some of the re-labeled EPROMs I have from Aliexpress do not work, they maybe too slow.

**Comment by Robert-Di-Benedetto** [comment]
Ok.  I will order a few other ROMs and give them a try.  M27C2001-10F1 (256K 100ns), 27C010-70 (128K 70ns) and 27C040-70 (512K 70ns).  I'll circle back when I have the test results.  In the meantime, if you have any other ROM suggestions, I'm happy to try them if I can source them.

**Comment by Scyllinice** [comment]
I can confirm that a `W27C020-70Z` works fine so I would assume the 27C010-70 or 27C040-70 will work too.

**Comment by Robert-Di-Benedetto** [comment]
I've just ordered a W27C020-70Z as well.  I'll double confirm when it arrives.  It will be good to have a list of multiple eprom options so sourcing can be easier.

**Comment by Scyllinice** [comment]
For clarity, I posted on the Snappy issue as well that I did update my eprom to the Snappy rom and put it in my SuperClone board and it worked right away.

**Comment by Robert-Di-Benedetto** [comment]
So far I have confirmed the following:
M27C2001-10F1 does NOT work
AM27HB010-70DC (128k) DOES work
AM27C040-70DC (512k) DOES work

Still waiting on delivery of W27C020-70Z

**Comment by Robert-Di-Benedetto** [comment]
I have now double-confirmed that W27C020-70Z also works.  So we now have 3 confirmed working ROMs.

**Comment by Kalidomra** [comment]
The Windbond W27C010-70 and W27E010-70 work. You need to change the 28 pin socket to a 32 pin. The new snappy rom also works. It is 128k so it will only work with a 32 pin chip.
