### ISSUE TITLE
PLA Issue

### ISSUE THREAD

**Issue by thegoat1973** [Kalidomra/SuperClone-5.0#7]
I built a couple of these with 15ns GAL and 45ns WinBond EEPROMs.  The cartridge starts up fine and exits to Basic, however after pressing the freeze button and resuming the program it crashes. If I switch out the PLA to a GAL PLA I don't have this issue, and I've tried on 3 different machines with the same results. Anyone else have this issue??

**Comment by Kalidomra** [comment]
What is the part number of the GAL you are using?

**Comment by thegoat1973** [comment]
I'm using an Atmel ATF16V8B-15PU in the cartridge

**Comment by Kalidomra** [comment]
Is it the ATF16V8B-15PU that is having issues? You mentioned you switched it out to a different chip.

**Comment by thegoat1973** [comment]
Sorry, my initial post wasn't very clear on that. The machine that the cartridge works on has a GAL based PLA chip replacement in it. If I use a stock MOS PLA in the machine the SS5 crashes on Resume. I've tried this on 2 breadbin C64 and a newer model 64C. The GAL PLA is a PLA replacement based on the GAL 20V8B and is meant as a drop in replacement for dead PLA chips in C64's.

**Comment by Kalidomra** [comment]
Are you sure the MOS PLA works?  It could also be the EEPROM you used. I have had issues with a few different ones.

**Comment by thegoat1973** [comment]
The machines all work with the stock PLA's. I have an original SS4 which works correctly in them as well as a SS5 image on a 1541 Ultimate II+ that works flawlessly. I've tried 4 different EEPROMS and 2 different GAL's in the PCB with same result. I'm starting to think the problem may be with the PCB's I ordered from PCBWay. I'll have to have a closer look at them.

**Comment by thegoat1973** [comment]
I took a closer look at the PCB and everything looks to be okay on the board. What type of EEPROM have you had success with and which ones have not worked?

**Comment by Kalidomra** [comment]
W27C512-45Z
W27C010-70 or W27C020-70
